// System message patterns used to identify proactive/automated messages
// These patterns help determine if a message should be treated as voice-only

export const SYSTEM_MESSAGE_PATTERNS = [
  // Creator/identity related patterns
  'who made you',
  'who created you', 
  'who developed you',
  'who built you',
  'i was created by',
  'i was made by',
  'i was developed by',
  'i was built by',
  'my creators are',
  'my developers are',
  
  // Proactive/greeting patterns
  'hello, how are you feeling today',
  'welcome',
  'good morning',
  'good afternoon', 
  'good evening',
  'good night',
  'rise and shine',
  'wakey wakey',
  'hope you had a good sleep',
  'hope you slept well',
  'time to wake up',
  'morning sunshine',
  'sweet dreams',
  'top of the morning',
  'greetings',
  'salutations',
  'hello there',
  'hey buddy',
  'howdy',
  'what\'s up',
  'hiya',
  'well hello',
  
  // Check-in patterns
  'it\'s been a while',
  'how have you been',
  'what would you like to talk about',
  'let\'s chat about',
  'what\'s on your mind',
  'how can i help you today',
  'how was your day',
  'how are you doing',
  'how are you feeling',
  'thinking of you',
  'hope you\'re well',
  'hope you\'re having a good day',
  'just checking in',
  'wanted to see how you are',
  'how\'s everything going',
  'how\'s your morning',
  'how\'s your evening',
  'how\'s your day going',
  'how\'s it going',
  'what\'s happening',
  'how are you holding up',
  'how\'s your mood',
  'what\'s your vibe today',
  'feeling okay today',
  'everything alright',
  'how\'s your heart',
  'what\'s in your heart today',
  'how\'s your spirit',
  'how are you mentally',
  'how\'s your energy',
  'feeling good today',
  'you doing okay',
  'how\'s your soul',
  
  // Additional proactive message patterns
  'how are things',
  'what\'s new',
  'thinking about you',
  'hope all is well',
  'how\'s life',
  'what\'s going on',
  'how are you today',
  'hope you\'re doing well',
  'checking on you',
  'how was your night',
  'sleep well',
  'have a great day',
  'take care',
  'wishing you well',
  'hope your day is going well',
  'hope you\'re having a wonderful day',
  'just wanted to say hi',
  'sending you love',
  'hope everything is okay',
  'how\'s your week',
  'hope you\'re staying safe',
  'just thinking of you',
  'how\'s life treating you',
  'what\'s been going on',
  'hope you\'re thriving',
  'sending good vibes',
  'hope you\'re smiling',
  'missing you',
  'hope you\'re happy',
  'you\'re amazing',
  'you matter',
  'you\'re important',
  'you\'re loved',
  'you\'re special',
  'proud of you',
  'believe in you',
  'rooting for you',
  'here for you',
  'care about you',
  
  // Emotional support patterns
  'how\'s your emotional state',
  'feeling overwhelmed',
  'need someone to talk to',
  'here to listen',
  'want to share anything',
  'anything troubling you',
  'how\'s your mental space',
  'feeling anxious lately',
  'everything overwhelming',
  'need a friendly ear',
  'want to vent',
  'feeling stressed',
  'need some support',
  'going through something',
  'tough time lately',
  'here if you need me',
  'always here for you',
  'never alone',
  'we\'re in this together',
  'you\'re stronger than you know',
  'this too shall pass',
  'better days ahead',
  'you\'ve got this',
  'one day at a time',
  'breathe and relax',
  'it\'s okay to not be okay',
  'your feelings are valid',
  
  // Scheduled/automated message patterns
  'this is your daily reminder',
  'this is your morning message',
  'this is your scheduled check-in',
  'automated message',
  'daily check-in',
  'morning check-in',
  'evening check-in',
  'scheduled message',
  'proactive message',
  'system message',
  'timed message',
  'recurring check-in',
  'periodic reminder',
  'routine message',
  'automated outreach',
  'scheduled reminder',
  'timer-based message',
  'calendar reminder',
  'daily prompt',
  'weekly check-up',
  'monthly reflection',
  
  // Time-based greetings (common in schedulers)
  'good morning! how are you',
  'morning! how did you sleep',
  'hey there! how are you feeling',
  'hi! how\'s your day',
  'hello! hope you\'re well',
  'hey! thinking of you',
  'hi there! how are things',
  'good morning, dear',
  'morning, sunshine',
  'hey beautiful',
  'hey handsome',
  'hello gorgeous',
  'hi lovely',
  'afternoon! how\'s it going',
  'evening! how was your day',
  'night owl! still up',
  'late night thoughts',
  'midnight check-in',
  'dawn is breaking',
  'sunrise greetings',
  'sunset reflections',
  'midday pause',
  'lunch break chat',
  'coffee time check-in',
  'tea time talk',
  'weekend vibes',
  'monday motivation',
  'friday feeling',
  'happy hump day',
  'throwback thursday',
  'thankful thursday',
  'wonderful wednesday',
  'terrific tuesday',
  'super saturday',
  'sunday funday',
  
  // Scheduler-style check-ins
  'time for your daily check-in',
  'your daily wellness check',
  'daily mental health check',
  'how are you doing today',
  'checking in on you today',
  'hope you\'re having a lovely day',
  'wanted to check how you\'re feeling',
  'just wanted to reach out',
  'sending you positive vibes',
  'hope your morning is going well',
  'hope you\'re starting your day well',
  'time for reflection',
  'moment of mindfulness',
  'pause and breathe',
  'self-care reminder',
  'wellness Wednesday',
  'mindful Monday',
  'therapeutic Thursday',
  'feel-good Friday',
  'soulful Sunday',
  'check-in time',
  'how\'s your progress',
  'tracking your mood',
  'emotional temperature check',
  'inner weather report',
  'heart status update',
  
  // Common proactive AI patterns
  'i\'ve been thinking about our conversation',
  'how has your week been',
  'hope you\'re taking care of yourself',
  'remember to take care of yourself',
  'don\'t forget to check in with yourself',
  'how are you really doing',
  'what\'s been on your mind lately',
  'how are you feeling right now',
  'hope you\'re being kind to yourself',
  'sending you warm thoughts',
  'hope you feel loved today',
  'you\'re in my thoughts',
  'hope today brings you joy',
  'wishing you peace today',
  'reflecting on our chat',
  'been pondering your words',
  'your story stays with me',
  'touched by your sharing',
  'inspired by your journey',
  'admire your strength',
  'grateful for your openness',
  'honored to know you',
  'appreciate your trust',
  'value our connection',
  'cherish our conversations',
  'thankful for you',
  'blessed to chat with you',
  'privilege to listen',
  'happy to support you',
  'glad you\'re here',
  'wonderful to meet you',
  'pleasure knowing you',
  
  // Motivational and inspirational patterns
  'you\'re doing great',
  'keep going',
  'don\'t give up',
  'stay strong',
  'you\'re resilient',
  'believe in yourself',
  'trust the process',
  'embrace the journey',
  'celebrate small wins',
  'progress not perfection',
  'you\'re enough',
  'be gentle with yourself',
  'practice self-compassion',
  'honor your feelings',
  'listen to your heart',
  'trust your instincts',
  'follow your dreams',
  'chase your passions',
  'live authentically',
  'be true to yourself',
  'shine your light',
  'spread your wings',
  'reach for the stars',
  'sky\'s the limit',
  'anything is possible',
  'you have potential',
  'limitless possibilities',
  'bright future ahead',
  'exciting times coming',
  'adventures await',
  
  // Backend scheduler identifiers
  'scheduled notification',
  'automatic check-in',
  'daily wellness reminder',
  'proactive outreach',
  'system notification',
  'automated wellness check',
  'scheduled wellness message',
  'daily mental health reminder',
  'cron job message',
  'background task',
  'scheduled task',
  'timer trigger',
  'webhook notification',
  'api scheduled call',
  'database trigger',
  'event-driven message',
  'queue processed',
  'batch job result',
  'scheduled service',
  'automated service',
  'system-generated',
  'bot-initiated',
  'ai-triggered',
  'algorithm-generated',
  'ml-powered message',
  'smart notification',
  'intelligent reminder',
  'predictive message',
  'contextual prompt',
  'adaptive check-in',
  
  // Comprehensive reminder patterns
  'reminder',
  'remind you',
  'don\'t forget',
  'time to',
  'it\'s time',
  'scheduled for',
  'appointment reminder',
  'meeting reminder',
  'task reminder',
  'due today',
  'due soon',
  'overdue',
  'deadline approaching',
  'follow up',
  'follow-up',
  'check back',
  'touch base',
  'circle back',
  'time for your',
  'your reminder',
  'notification:',
  'alert:',
  'reminder:',
  'schedule reminder',
  'recurring reminder',
  'daily reminder',
  'weekly reminder',
  'monthly reminder',
  'medication reminder',
  'appointment in',
  'meeting in',
  'task due',
  'deadline reminder',
  'calendar alert',
  'calendar reminder',
  'upcoming event',
  'coming up',
  'scheduled event',
  'planned activity',
  'preset reminder',
  'automatic reminder',
  'smart reminder',
  'ai reminder',
  'personal reminder',
  'custom reminder',
  'important reminder',
  'urgent reminder',
  'priority reminder',
  'gentle reminder',
  'friendly reminder',
  'kind reminder',
  'polite reminder',
  'timely reminder',
  'helpful reminder',
  'useful reminder',
  'handy reminder',
  'convenient reminder',
  'practical reminder',
  'effective reminder',
  'reliable reminder',
  'consistent reminder',
  'regular reminder',
  'routine reminder',
  'habit reminder',
  'lifestyle reminder',
  'wellness reminder',
  'health reminder',
  'fitness reminder',
  'exercise reminder',
  'workout reminder',
  'nutrition reminder',
  'hydration reminder',
  'sleep reminder',
  'bedtime reminder',
  'wake up reminder',
  'morning reminder',
  'evening reminder',
  'night reminder',
  'lunch reminder',
  'dinner reminder',
  'breakfast reminder',
  'meal reminder',
  'snack reminder',
  'water reminder',
  'break reminder',
  'rest reminder',
  'stretch reminder',
  'movement reminder',
  'posture reminder',
  'breathing reminder',
  'meditation reminder',
  'mindfulness reminder',
  'gratitude reminder',
  'journal reminder',
  'diary reminder',
  'reflection reminder',
  'goal reminder',
  'progress reminder',
  'milestone reminder',
  'achievement reminder',
  'celebration reminder',
  'anniversary reminder',
  'birthday reminder',
  'holiday reminder',
  'vacation reminder',
  'trip reminder',
  'travel reminder',
  'packing reminder',
  'preparation reminder',
  'planning reminder',
  'organization reminder',
  'cleaning reminder',
  'maintenance reminder',
  'repair reminder',
  'service reminder',
  'renewal reminder',
  'subscription reminder',
  'payment reminder',
  'bill reminder',
  'invoice reminder',
  'tax reminder',
  'insurance reminder',
  'document reminder',
  'paperwork reminder',
  'application reminder',
  'registration reminder',
  'booking reminder',
  'reservation reminder',
  'confirmation reminder',
  'verification reminder',
  'update reminder',
  'upgrade reminder',
  'backup reminder',
  'security reminder',
  'password reminder',
  'login reminder',
  'account reminder',
  'profile reminder',
  'settings reminder',
  'preference reminder',
  'configuration reminder',
  'installation reminder',
  'download reminder',
  'upload reminder',
  'sync reminder',
  'connection reminder',
  'network reminder',
  'wifi reminder',
  'internet reminder',
  'data reminder',
  'storage reminder',
  'memory reminder',
  'space reminder',
  'capacity reminder',
  'limit reminder',
  'quota reminder',
  'usage reminder',
  'consumption reminder',
  'monitoring reminder',
  'tracking reminder',
  'logging reminder',
  'recording reminder',
  'documentation reminder',
  'reporting reminder',
  'analysis reminder',
  'review reminder',
  'evaluation reminder',
  'assessment reminder',
  'feedback reminder',
  'survey reminder',
  'questionnaire reminder',
  'form reminder',
  'submission reminder',
  'deadline today',
  'due in',
  'expires today',
  'expires soon',
  'expiring',
  'renewal due',
  'subscription ending',
  'trial ending',
  'license expiring',
  'warranty expiring',
  'contract ending',
  'agreement expiring',
  'policy expiring',
  'coverage ending',
  'plan expiring',
  'membership ending',
  'access expiring',
  'permission ending',
  'authorization expiring',
  'certification expiring',
  'qualification ending',
  'training reminder',
  'course reminder',
  'class reminder',
  'lesson reminder',
  'session reminder',
  'workshop reminder',
  'seminar reminder',
  'webinar reminder',
  'conference reminder',
  'event reminder',
  'occasion reminder',
  'celebration reminder',
  'party reminder',
  'gathering reminder',
  'social reminder',
  'community reminder',
  'group reminder',
  'team reminder',
  'family reminder',
  'friend reminder',
  'relationship reminder',
  'communication reminder',
  'contact reminder',
  'call reminder',
  'email reminder',
  'message reminder',
  'text reminder',
  'chat reminder',
  'video reminder',
  'audio reminder',
  'voice reminder',
  'sound reminder',
  'alarm reminder',
  'notification reminder',
  'alert reminder',
  'warning reminder',
  'notice reminder',
  'announcement reminder',
  'broadcast reminder',
  'update notification',
  'status reminder',
  'progress notification',
  'completion reminder',
  'success reminder',
  'failure reminder',
  'error reminder',
  'issue reminder',
  'problem reminder',
  'solution reminder',
  'fix reminder',
  'repair notification',
  'maintenance notification',
  'service notification',
  'support reminder',
  'help reminder',
  'assistance reminder',
  'guidance reminder',
  'instruction reminder',
  'direction reminder',
  'step reminder',
  'process reminder',
  'procedure reminder',
  'protocol reminder',
  'guideline reminder',
  'rule reminder',
  'policy reminder',
  'regulation reminder',
  'compliance reminder',
  'requirement reminder',
  'obligation reminder',
  'responsibility reminder',
  'duty reminder',
  'task notification',
  'assignment reminder',
  'project reminder',
  'work reminder',
  'job reminder',
  'career reminder',
  'professional reminder',
  'business reminder',
  'client reminder',
  'customer reminder',
  'service reminder',
  'product reminder',
  'order reminder',
  'delivery reminder',
  'shipping reminder',
  'tracking reminder',
  'status update',
  'progress update',
  'completion notification',
  'achievement notification',
  'milestone notification',
  'goal notification',
  'target reminder',
  'objective reminder',
  'purpose reminder',
  'mission reminder',
  'vision reminder',
  'value reminder',
  'principle reminder',
  'belief reminder',
  'commitment reminder',
  'promise reminder',
  'pledge reminder',
  'vow reminder',
  'oath reminder',
  'agreement reminder',
  'contract reminder',
  'deal reminder',
  'arrangement reminder',
  'understanding reminder',
  'consensus reminder',
  'decision reminder',
  'choice reminder',
  'selection reminder',
  'option reminder',
  'alternative reminder',
  'possibility reminder',
  'opportunity reminder',
  'chance reminder',
  'moment reminder',
  'time reminder',
  'period reminder',
  'duration reminder',
  'interval reminder',
  'frequency reminder',
  'schedule notification',
  'timetable reminder',
  'calendar notification',
  'agenda reminder',
  'plan reminder',
  'itinerary reminder',
  'route reminder',
  'path reminder',
  'journey reminder',
  'trip notification',
  'travel notification',
  'destination reminder',
  'location reminder',
  'place reminder',
  'venue reminder',
  'address reminder',
  'contact reminder',
  'information reminder',
  'detail reminder',
  'fact reminder',
  'data reminder',
  'record reminder',
  'file reminder',
  'document notification',
  'report reminder',
  'summary reminder',
  'overview reminder',
  'description reminder',
  'explanation reminder',
  'clarification reminder',
  'instruction notification',
  'guidance notification',
  'advice reminder',
  'suggestion reminder',
  'recommendation reminder',
  'proposal reminder',
  'offer reminder',
  'invitation reminder',
  'request reminder',
  'inquiry reminder',
  'question reminder',
  'answer reminder',
  'response reminder',
  'reply reminder',
  'feedback notification',
  'comment reminder',
  'review notification',
  'rating reminder',
  'evaluation notification',
  'assessment notification',
  'analysis reminder',
  'examination reminder',
  'inspection reminder',
  'audit reminder',
  'check reminder',
  'verification notification',
  'confirmation notification',
  'approval reminder',
  'authorization notification',
  'permission reminder',
  'access notification',
  'entry reminder',
  'admission reminder',
  'registration notification',
  'enrollment reminder',
  'subscription notification',
  'membership notification',
  'participation reminder',
  'involvement reminder',
  'engagement reminder',
  'activity reminder',
  'action reminder',
  'behavior reminder',
  'habit notification',
  'routine notification',
  'custom notification',
  'personal notification',
  'individual reminder',
  'specific reminder',
  'particular reminder',
  'special reminder',
  'unique reminder',
  'exclusive reminder',
  'private reminder',
  'confidential reminder',
  'secure reminder',
  'protected reminder',
  'encrypted reminder',
  'safe reminder',
  'trusted reminder',
  'verified reminder',
  'authenticated reminder',
  'authorized reminder',
  'validated reminder',
  'confirmed reminder',
  'certified reminder',
  'approved reminder',
  'endorsed reminder',
  'recommended reminder',
  'suggested reminder',
  'proposed reminder',
  'offered reminder',
  'presented reminder',
  'delivered reminder',
  'sent reminder',
  'received reminder',
  'processed reminder',
  'handled reminder',
  'managed reminder',
  'controlled reminder',
  'monitored reminder',
  'tracked reminder',
  'observed reminder',
  'recorded reminder',
  'logged reminder',
  'documented reminder',
  'reported reminder',
  'notified reminder',
  'alerted reminder',
  'warned reminder',
  'informed reminder',
  'updated reminder',
  'refreshed reminder',
  'renewed reminder',
  'restored reminder',
  'recovered reminder',
  'retrieved reminder',
  'recalled reminder',
  'remembered reminder',
  'memorized reminder',
  'learned reminder',
  'studied reminder',
  'researched reminder',
  'investigated reminder',
  'explored reminder',
  'discovered reminder',
  'found reminder',
  'located reminder',
  'identified reminder',
  'recognized reminder',
  'detected reminder',
  'noticed reminder',
  'observed reminder',
  'seen reminder',
  'watched reminder',
  'monitored reminder',
  'supervised reminder',
  'overseen reminder',
  'managed reminder',
  'directed reminder',
  'guided reminder',
  'led reminder',
  'coordinated reminder',
  'organized reminder',
  'arranged reminder',
  'planned reminder',
  'scheduled reminder',
  'programmed reminder',
  'set reminder',
  'configured reminder',
  'established reminder',
  'created reminder',
  'generated reminder',
  'produced reminder',
  'made reminder',
  'built reminder',
  'constructed reminder',
  'developed reminder',
  'designed reminder',
  'crafted reminder',
  'formed reminder',
  'shaped reminder',
  'molded reminder',
  'fashioned reminder',
  'tailored reminder',
  'customized reminder',
  'personalized reminder',
  'individualized reminder',
  'specialized reminder',
  'optimized reminder',
  'enhanced reminder',
  'improved reminder',
  'upgraded reminder',
  'advanced reminder',
  'sophisticated reminder',
  'intelligent reminder',
  'smart reminder',
  'clever reminder',
  'wise reminder',
  'insightful reminder',
  'thoughtful reminder',
  'considerate reminder',
  'caring reminder',
  'loving reminder',
  'kind reminder',
  'gentle reminder',
  'soft reminder',
  'mild reminder',
  'subtle reminder',
  'discreet reminder',
  'quiet reminder',
  'silent reminder',
  'peaceful reminder',
  'calm reminder',
  'serene reminder',
  'tranquil reminder',
  'relaxed reminder',
  'comfortable reminder',
  'pleasant reminder',
  'enjoyable reminder',
  'delightful reminder',
  'wonderful reminder',
  'amazing reminder',
  'fantastic reminder',
  'excellent reminder',
  'outstanding reminder',
  'exceptional reminder',
  'remarkable reminder',
  'extraordinary reminder',
  'incredible reminder',
  'unbelievable reminder',
  'astonishing reminder',
  'surprising reminder',
  'unexpected reminder',
  'sudden reminder',
  'immediate reminder',
  'instant reminder',
  'quick reminder',
  'fast reminder',
  'rapid reminder',
  'speedy reminder',
  'swift reminder',
  'prompt reminder',
  'timely reminder',
  'punctual reminder',
  'precise reminder',
  'accurate reminder',
  'exact reminder',
  'correct reminder',
  'right reminder',
  'proper reminder',
  'appropriate reminder',
  'suitable reminder',
  'fitting reminder',
  'relevant reminder',
  'applicable reminder',
  'pertinent reminder',
  'related reminder',
  'connected reminder',
  'linked reminder',
  'associated reminder',
  'attached reminder',
  'joined reminder',
  'united reminder',
  'combined reminder',
  'merged reminder',
  'integrated reminder',
  'synchronized reminder',
  'coordinated reminder',
  'aligned reminder',
  'matched reminder',
  'paired reminder',
  'coupled reminder',
  'bonded reminder',
  'connected reminder',
  'networked reminder',
  'online reminder',
  'digital reminder',
  'electronic reminder',
  'virtual reminder',
  'cyber reminder',
  'internet reminder',
  'web reminder',
  'cloud reminder',
  'remote reminder',
  'distant reminder',
  'far reminder',
  'close reminder',
  'near reminder',
  'nearby reminder',
  'local reminder',
  'regional reminder',
  'national reminder',
  'international reminder',
  'global reminder',
  'worldwide reminder',
  'universal reminder',
  'general reminder',
  'common reminder',
  'standard reminder',
  'normal reminder',
  'regular reminder',
  'ordinary reminder',
  'typical reminder',
  'usual reminder',
  'conventional reminder',
  'traditional reminder',
  'classic reminder',
  'basic reminder',
  'simple reminder',
  'easy reminder',
  'straightforward reminder',
  'clear reminder',
  'obvious reminder',
  'evident reminder',
  'apparent reminder',
  'visible reminder',
  'noticeable reminder',
  'observable reminder',
  'detectable reminder',
  'recognizable reminder',
  'identifiable reminder',
  'distinguishable reminder',
  'discernible reminder',
  'perceptible reminder',
  'sensible reminder',
  'logical reminder',
  'reasonable reminder',
  'rational reminder',
  'practical reminder',
  'realistic reminder',
  'feasible reminder',
  'possible reminder',
  'achievable reminder',
  'attainable reminder',
  'reachable reminder',
  'accessible reminder',
  'available reminder',
  'obtainable reminder',
  'manageable reminder',
  'controllable reminder',
  'adjustable reminder',
  'modifiable reminder',
  'changeable reminder',
  'alterable reminder',
  'variable reminder',
  'flexible reminder',
  'adaptable reminder',
  'versatile reminder',
  'multifunctional reminder',
  'multipurpose reminder',
  'comprehensive reminder',
  'complete reminder',
  'full reminder',
  'total reminder',
  'entire reminder',
  'whole reminder',
  'all reminder',
  'every reminder',
  'each reminder',
  'individual reminder',
  'single reminder',
  'one reminder',
  'first reminder',
  'last reminder',
  'final reminder',
  'ultimate reminder',
  'best reminder',
  'top reminder',
  'highest reminder',
  'maximum reminder',
  'peak reminder',
  'supreme reminder',
  'superior reminder',
  'premium reminder',
  'deluxe reminder',
  'luxury reminder',
  'exclusive reminder',
  'elite reminder',
  'professional reminder',
  'expert reminder',
  'master reminder',
  'advanced reminder',
  'pro reminder',
  'plus reminder',
  'extra reminder',
  'bonus reminder',
  'special reminder',
  'limited reminder',
  'rare reminder',
  'unique reminder',
  'original reminder',
  'authentic reminder',
  'genuine reminder',
  'real reminder',
  'true reminder',
  'actual reminder',
  'factual reminder',
  'honest reminder',
  'sincere reminder',
  'trustworthy reminder',
  'reliable reminder',
  'dependable reminder',
  'consistent reminder',
  'stable reminder',
  'steady reminder',
  'constant reminder',
  'continuous reminder',
  'ongoing reminder',
  'persistent reminder',
  'lasting reminder',
  'enduring reminder',
  'permanent reminder',
  'eternal reminder',
  'infinite reminder',
  'unlimited reminder',
  'boundless reminder',
  'endless reminder',
  'never-ending reminder',
  'perpetual reminder',
  'everlasting reminder',
  'immortal reminder',
  'timeless reminder',
  'ageless reminder',
  'ancient reminder',
  'old reminder',
  'vintage reminder',
  'classic reminder',
  'retro reminder',
  'historical reminder',
  'past reminder',
  'previous reminder',
  'former reminder',
  'earlier reminder',
  'prior reminder',
  'before reminder',
  'initial reminder',
  'starting reminder',
  'beginning reminder',
  'opening reminder',
  'introductory reminder',
  'preliminary reminder',
  'preparatory reminder',
  'advance reminder',
  'preview reminder',
  'pre-reminder',
  'early reminder',
  'soon reminder',
  'upcoming reminder',
  'approaching reminder',
  'coming reminder',
  'next reminder',
  'following reminder',
  'subsequent reminder',
  'later reminder',
  'future reminder',
  'tomorrow reminder',
  'next week reminder',
  'next month reminder',
  'next year reminder',
  'annual reminder',
  'yearly reminder',
  'seasonal reminder',
  'quarterly reminder',
  'monthly reminder',
  'bi-weekly reminder',
  'weekly reminder',
  'daily reminder',
  'hourly reminder',
  'minute reminder',
  'second reminder',
  'moment reminder',
  'instant reminder',
  'immediate reminder',
  'now reminder',
  'current reminder',
  'present reminder',
  'today reminder',
  'tonight reminder',
  'this morning reminder',
  'this afternoon reminder',
  'this evening reminder'
];

// Helper function to check if text matches system patterns
export function isSystemMessageContent(text) {
  if (!text || typeof text !== 'string') return false;
  
  const lowerText = text.toLowerCase();
  return SYSTEM_MESSAGE_PATTERNS.some(pattern => 
    lowerText.includes(pattern.toLowerCase())
  );
}

// Alias for backward compatibility and consistency with other imports
export const systemPatterns = SYSTEM_MESSAGE_PATTERNS;
