name: CI/CD Pipeline

on:
  push:
    paths:
      - 'chatbot-new-frontend/**'
    branches:
      - 'main'
  pull_request:
    paths:
      - 'chatbot-new-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Debug:Print next.config.mjs to confirm fix
        run: cat chatbot-new-frontend/next.config.mjs

      - name: Install dependencies
        working-directory: chatbot-new-frontend
        run: npm install

      - name: Build project
        working-directory: chatbot-new-frontend
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}
      
      - name: Authenticate with Google Cloud via Workload Identity
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/283192146773/locations/global/workloadIdentityPools/github-actions-pool/providers/github'
          service_account: 'github-actions-deployer@novife.iam.gserviceaccount.com'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: novife

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy novife-frontend \
            --source=./chatbot-new-frontend \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated

