name: CI/CD Pipeline

on:
  push:
    paths:
      - 'chatbot-new-frontend/src/**'
    branches:
      - main
  pull_request:
    paths:
      - 'chatbot-new-frontend/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: NoviFE
        run: npm install

      - name: Build project
        run: npm run build

      - name: Export static site (for Next.js)
        run: npm run export

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out



     
    
   
 
 
